### ISSUE TITLE
Extended numpad keys

### ISSUE THREAD

**Issue by theen** [benblazak/ergodox-firmware#50]
I looked through the keyboard.h and I can they're not supported on any platform. Why is that? I looked through the rewrites' equivalent and they're absent entirely. Will they never be supported? If so I'm curious for the technical reason.  I'd hoped my layout could e.g. always send an ' @ ' rather than a ' " ' regardless of the OS's regional layout.

**Comment by theen** [comment]
(it didn't work)

**Comment by benblazak** [comment]
Sorry about that :-/ -- I just closed the issue because it's almost a year old, and I'm pretty sure it's a driver problem.
