### ISSUE TITLE
HID usage table pdf has new URL

### ISSUE THREAD

**Issue by hubgitti** [benblazak/ergodox-firmware#68]
The URL of the HID usage table pdf file mentioned in src/lib/usb/usage-page/keyboard.h moved to http://www.usb.org/developers/hidpage#HID_Usage

**Comment by hubgitti** [comment]
The exact link is: http://www.usb.org/developers/hidpage/Hut1_12v2.pdf

**Comment by benblazak** [comment]
Updated.  Thanks.

**Comment by theLMGN** [comment]
Might want to know that this has been deleted, see https://web.archive.org/web/20180827225742if_/http://www.usb.org/developers/hidpage/Hut1_12v2.pdf
