### ISSUE TITLE
Always switched to layer 2 on the first system startup

### ISSUE THREAD

**Issue by neur1n** [benblazak/ergodox-firmware#92]
I don't know how to make a proper title, because it seems really weird to me. So I always use layer 0 with a computer of Windows 10, and I turn off it when I finish my work. The second day I start the computer for the very first time, the keyboard always switches to layer 2 (the last layer) automatically. Previously I plugged this keyboard into a linux machine, everything worked fine. I thought it might be the big-endian/little-endian issue, so I erased and download the firmware on Windows again. But nothing changed.

Any suggestion is much appreciated.

(PS: my configuration can be found [here](https://github.com/Neur1n/ergodox-layout).)

**Comment by benblazak** [comment]
Don’t have time to look into it right now — but my first thought is that maybe it has something to do with the way caps lock (or another key like that) is handled?

**Comment by neur1n** [comment]
Additionally, it seems that only the right part is working during boot. I can tell it since I cannot switch the layers using the keys on the left part, and nothings happens when I try to type something with the left part.
![image](https://user-images.githubusercontent.com/17579247/75733830-4162dc00-5d31-11ea-9998-fdf9a66d5656.png)

**Comment by benblazak** [comment]
Might be a hardware problem, if you haven’t double checked that yet.
